# Generated by Django 5.2 on 2025-04-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="书名")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="book_covers/", verbose_name="封面图片"
                    ),
                ),
            ],
            options={
                "verbose_name": "书籍",
                "verbose_name_plural": "书籍",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="章节号")),
                ("title", models.CharField(max_length=200, verbose_name="章节标题")),
                ("introduction", models.TextField(blank=True, verbose_name="章节介绍")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.book",
                        verbose_name="所属书籍",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="小节号")),
                ("title", models.CharField(max_length=200, verbose_name="小节标题")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "小节",
                "verbose_name_plural": "小节",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="知识点标题")),
                ("content", models.TextField(verbose_name="知识点内容")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_points",
                        to="courses.section",
                        verbose_name="所属小节",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "单项选择题"),
                            ("multiple", "多项选择题"),
                            ("comprehensive", "综合题"),
                        ],
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="题号")),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项"),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="答案")),
                ("explanation", models.TextField(verbose_name="解析")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="courses.section",
                        verbose_name="所属小节",
                    ),
                ),
            ],
            options={
                "verbose_name": "习题",
                "verbose_name_plural": "习题",
                "ordering": ["order", "number"],
            },
        ),
    ]
