# Generated by Django 5.2 on 2025-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("content", "内容小节"),
                    ("introduction", "章节介绍"),
                    ("summary", "章节小结"),
                    ("faq", "常见问题/疑难点"),
                    ("other", "其他"),
                ],
                default="content",
                max_length=20,
                verbose_name="小节类型",
            ),
        ),
    ]
