# Generated by Django 5.2 on 2025-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_section_section_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="content",
            field=models.TextField(blank=True, verbose_name="小节内容 (Markdown)"),
        ),
    ]
