# Generated by Django 5.2 on 2025-04-29 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_usermistakecollection_last_wrong_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        help_text="生成该题目的AI模型类型，如grok, deepseek等",
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multiple", "多选题"),
                            ("comprehensive", "综合题"),
                        ],
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项"),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="答案")),
                ("explanation", models.TextField(verbose_name="解析")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "knowledge_points",
                    models.JSONField(blank=True, null=True, verbose_name="相关知识点"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="推荐理由")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_exercises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI生成习题",
                "verbose_name_plural": "AI生成习题",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                (
                    "user_answer",
                    models.TextField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="尝试时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_exercise_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="courses.aigeneratedexercise",
                        verbose_name="AI生成习题",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI生成习题答题记录",
                "verbose_name_plural": "AI生成习题答题记录",
                "ordering": ["-attempt_time"],
            },
        ),
    ]
