# Generated by Django 5.2 on 2025-05-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_aigeneratedexercise_aiexerciseattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigeneratedexercise",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_exercises",
                to="courses.book",
                verbose_name="关联书籍",
            ),
        ),
    ]
