# Generated by Django 5.2 on 2025-05-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_aigeneratedexercise_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(max_length=100, verbose_name="书籍名称"),
                ),
                (
                    "chapter_number",
                    models.CharField(max_length=10, verbose_name="章节号"),
                ),
                (
                    "section_number",
                    models.CharField(max_length=10, verbose_name="小节号"),
                ),
                (
                    "section_title",
                    models.CharField(max_length=200, verbose_name="小节标题"),
                ),
                (
                    "problem_types",
                    models.JSONField(
                        help_text="可包含题干有误、选项有误、答案有误等",
                        verbose_name="问题类型",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="详细描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="管理员备注"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="courses.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "习题反馈",
                "verbose_name_plural": "习题反馈",
                "ordering": ["-created_at"],
            },
        ),
    ]
