# Generated by Django 5.2 on 2025-04-29 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_userexerciseattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        default=5,
                        help_text="1-10，数值越大表示相关性越强",
                        verbose_name="相关性程度",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_knowledge_links",
                        to="courses.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_knowledge_links",
                        to="courses.knowledge",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "习题-知识点关联",
                "verbose_name_plural": "习题-知识点关联",
                "unique_together": {("exercise", "knowledge")},
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="knowledge_points",
            field=models.ManyToManyField(
                related_name="related_exercises",
                through="courses.ExerciseKnowledge",
                to="courses.knowledge",
                verbose_name="相关知识点",
            ),
        ),
        migrations.CreateModel(
            name="UserMistakeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后一次尝试时间"
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, verbose_name="尝试次数"),
                ),
                (
                    "correct_count",
                    models.IntegerField(default=0, verbose_name="正确次数"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="笔记")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_mistake_collections",
                        to="courses.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistake_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户错题集",
                "verbose_name_plural": "用户错题集",
                "ordering": ["-added_at"],
                "unique_together": {("user", "exercise")},
            },
        ),
    ]
