# Generated by Django 5.2 on 2025-04-29 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_exerciseknowledge_exercise_knowledge_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                (
                    "user_answer",
                    models.TextField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="尝试时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts_new",
                        to="courses.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_attempts_new",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户答题记录(新)",
                "verbose_name_plural": "用户答题记录(新)",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.DeleteModel(
            name="UserExerciseAttempt",
        ),
    ]
