# Generated by Django 5.2 on 2025-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_exerciseattempt_delete_userexerciseattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermistakecollection",
            name="last_wrong_answer",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="最近一次错误答案"
            ),
        ),
    ]
